# Generated by Django 4.1.2 on 2022-10-28 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_animal', models.CharField(choices=[('M', 'Muerto'), ('V', 'Vivo'), ('P', 'En produccion')], default='V', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario_nombre', models.CharField(max_length=50)),
                ('propietario_apellido', models.CharField(max_length=50)),
                ('propietario_ci', models.PositiveIntegerField(unique=True)),
                ('propietario_ruc', models.CharField(max_length=50)),
                ('propietario_direccion', models.CharField(max_length=100)),
                ('propietario_telefono', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_animal', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.propietario')),
            ],
        ),
    ]
