# Generated by Django 4.1.2 on 2022-10-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0002_estado_propietario_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna_nombre', models.CharField(max_length=50)),
                ('vacuna_origen', models.CharField(max_length=50)),
                ('vacuna_dosis', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado_animal',
            field=models.CharField(choices=[('M', 'Muerto'), ('V', 'Vivo'), ('P', 'En produccion')], max_length=1),
        ),
        migrations.CreateModel(
            name='Vacuna_X_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.animal')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.vacuna')),
            ],
        ),
    ]
