# Generated by Django 4.1.2 on 2022-11-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0003_vacuna_animal_estado_alter_estado_estado_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='estado',
        ),
        migrations.AddField(
            model_name='animal',
            name='estado_animal',
            field=models.CharField(choices=[('M', 'Muerto'), ('V', 'Vivo'), ('P', 'En produccion')], default='V', max_length=1),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
